package models

import (
	"time"

	"github.com/google/uuid"
)

type WeeklyReviewStatus string

const (
	WeeklyReviewStatusPending   WeeklyReviewStatus = "pending"
	WeeklyReviewStatusCompleted WeeklyReviewStatus = "completed"
	WeeklyReviewStatusFailed    WeeklyReviewStatus = "failed"
)

// MoodArcDay is one day in the weekly mood chart.
type MoodArcDay struct {
	Date    string `json:"date"`     // YYYY-MM-DD
	AvgMood int    `json:"avg_mood"` // 1-100
}

// WeeklyReview is stored once per user per week, generated by Claude.
type WeeklyReview struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	WeekStart   time.Time          `json:"week_start"` // Sunday that triggered the review
	Narrative   string             `json:"narrative"`  // Claude-generated paragraph
	TopEmotions []string           `json:"top_emotions"`
	MoodArc     []MoodArcDay       `json:"mood_arc"`
	EntryCount  int                `json:"entry_count"`
	Status      WeeklyReviewStatus `json:"status"`
	ScheduledAt time.Time          `json:"scheduled_at"`
	GeneratedAt *time.Time         `json:"generated_at,omitempty"`
	CreatedAt   time.Time          `json:"created_at"`
}

// WeekSummaryEntry is the per-entry data fed into the weekly review prompt.
type WeekSummaryEntry struct {
	Date      time.Time
	Summary   string
	MoodScore int
	Emotions  []string // emotions with intensity >= 0.5
}
